/**
 * Documentation Generator Module
 * Generates markdown documentation from parsed code
 */

import { writeFile, mkdir } from 'fs/promises';
import { dirname, join, basename, relative } from 'path';
import type {
  ParsedFile,
  CodeBlock,
  DocumentationEntry,
  Config,
  HealthScore
} from '../types.js';

export interface GeneratorOptions {
  outputDir: string;
  format: 'markdown' | 'html' | 'json';
  generateTOC: boolean;
  includeSource: boolean;
  projectName?: string;
}

export async function generateDocumentation(
  files: ParsedFile[],
  healthScore: HealthScore,
  options: GeneratorOptions
): Promise<string[]> {
  const generatedFiles: string[] = [];

  await mkdir(options.outputDir, { recursive: true });

  switch (options.format) {
    case 'markdown':
      generatedFiles.push(...await generateMarkdown(files, healthScore, options));
      break;
    case 'json':
      generatedFiles.push(...await generateJSON(files, healthScore, options));
      break;
    case 'html':
      generatedFiles.push(...await generateHTML(files, healthScore, options));
      break;
  }

  return generatedFiles;
}

async function generateMarkdown(
  files: ParsedFile[],
  healthScore: HealthScore,
  options: GeneratorOptions
): Promise<string[]> {
  const generatedFiles: string[] = [];
  const projectName = options.projectName || 'Project';

  // Generate main README/index
  const mainDoc = generateMainDoc(files, healthScore, projectName, options.generateTOC);
  const mainPath = join(options.outputDir, 'README.md');
  await writeFile(mainPath, mainDoc);
  generatedFiles.push(mainPath);

  // Generate API reference
  const apiDoc = generateAPIReference(files);
  const apiPath = join(options.outputDir, 'API.md');
  await writeFile(apiPath, apiDoc);
  generatedFiles.push(apiPath);

  // Generate per-file documentation
  for (const file of files) {
    if (file.blocks.length === 0) continue;

    const fileDoc = generateFileDoc(file, options.includeSource);
    const docPath = join(
      options.outputDir,
      'files',
      file.info.relativePath.replace(/\.[^.]+$/, '.md')
    );

    await mkdir(dirname(docPath), { recursive: true });
    await writeFile(docPath, fileDoc);
    generatedFiles.push(docPath);
  }

  // Generate health report
  const healthDoc = generateHealthReport(healthScore);
  const healthPath = join(options.outputDir, 'HEALTH.md');
  await writeFile(healthPath, healthDoc);
  generatedFiles.push(healthPath);

  return generatedFiles;
}

async function generateJSON(
  files: ParsedFile[],
  healthScore: HealthScore,
  options: GeneratorOptions
): Promise<string[]> {
  const output = {
    projectName: options.projectName || 'Project',
    generatedAt: new Date().toISOString(),
    healthScore,
    files: files.map(f => ({
      path: f.info.relativePath,
      language: f.info.language,
      lines: f.info.lines,
      blocks: f.blocks.map(b => ({
        type: b.type,
        name: b.name,
        line: b.startLine,
        documented: !!b.documentation,
        complexity: b.complexity,
        parameters: b.parameters,
        returnType: b.returnType
      })),
      imports: f.imports,
      exports: f.exports
    }))
  };

  const outputPath = join(options.outputDir, 'documentation.json');
  await writeFile(outputPath, JSON.stringify(output, null, 2));
  return [outputPath];
}

async function generateHTML(
  files: ParsedFile[],
  healthScore: HealthScore,
  options: GeneratorOptions
): Promise<string[]> {
  const projectName = options.projectName || 'Project';
  const html = generateHTMLDocument(files, healthScore, projectName);
  const outputPath = join(options.outputDir, 'index.html');
  await writeFile(outputPath, html);
  return [outputPath];
}

function generateMainDoc(
  files: ParsedFile[],
  healthScore: HealthScore,
  projectName: string,
  includeTOC: boolean
): string {
  const totalFunctions = files.reduce((sum, f) =>
    sum + f.blocks.filter(b => b.type === 'function' || b.type === 'method').length, 0);
  const totalClasses = files.reduce((sum, f) =>
    sum + f.blocks.filter(b => b.type === 'class').length, 0);
  const totalInterfaces = files.reduce((sum, f) =>
    sum + f.blocks.filter(b => b.type === 'interface').length, 0);
  const totalLines = files.reduce((sum, f) => sum + f.info.lines, 0);

  const languageStats = new Map<string, number>();
  for (const file of files) {
    const count = languageStats.get(file.info.language) || 0;
    languageStats.set(file.info.language, count + 1);
  }

  let doc = `# ${projectName} Documentation

> Auto-generated by DocuMate

## Overview

| Metric | Value |
|--------|-------|
| Total Files | ${files.length} |
| Total Lines | ${totalLines.toLocaleString()} |
| Functions/Methods | ${totalFunctions} |
| Classes | ${totalClasses} |
| Interfaces/Types | ${totalInterfaces} |
| Health Score | ${getHealthEmoji(healthScore.overall)} ${healthScore.overall}/100 |

## Language Breakdown

| Language | Files |
|----------|-------|
${Array.from(languageStats.entries())
  .sort((a, b) => b[1] - a[1])
  .map(([lang, count]) => `| ${lang} | ${count} |`)
  .join('\n')}

## Health Summary

- **Documentation**: ${healthScore.categories.documentation}/100
- **Complexity**: ${healthScore.categories.complexity}/100
- **Structure**: ${healthScore.categories.structure}/100
- **Maintainability**: ${healthScore.categories.maintainability}/100

${healthScore.issues.length > 0 ? `
### Issues Found

${healthScore.issues.slice(0, 10).map(issue =>
  `- ${getSeverityEmoji(issue.severity)} **${issue.rule}**: ${issue.message}${issue.file ? ` (${issue.file}:${issue.line})` : ''}`
).join('\n')}

${healthScore.issues.length > 10 ? `\n_...and ${healthScore.issues.length - 10} more issues_\n` : ''}
` : ''}

${healthScore.suggestions.length > 0 ? `
### Suggestions

${healthScore.suggestions.map(s => `- ${s}`).join('\n')}
` : ''}
`;

  if (includeTOC) {
    doc += `
## Table of Contents

### Files

${files.map(f => `- [${f.info.relativePath}](files/${f.info.relativePath.replace(/\.[^.]+$/, '.md')})`).join('\n')}

### Quick Links

- [API Reference](API.md)
- [Health Report](HEALTH.md)
`;
  }

  return doc;
}

function generateAPIReference(files: ParsedFile[]): string {
  let doc = `# API Reference

> Auto-generated by DocuMate

`;

  // Group by type
  const functions: { block: CodeBlock; file: ParsedFile }[] = [];
  const classes: { block: CodeBlock; file: ParsedFile }[] = [];
  const interfaces: { block: CodeBlock; file: ParsedFile }[] = [];
  const types: { block: CodeBlock; file: ParsedFile }[] = [];

  for (const file of files) {
    for (const block of file.blocks) {
      const entry = { block, file };
      switch (block.type) {
        case 'function':
        case 'method':
          functions.push(entry);
          break;
        case 'class':
          classes.push(entry);
          break;
        case 'interface':
          interfaces.push(entry);
          break;
        case 'type':
          types.push(entry);
          break;
      }
    }
  }

  if (classes.length > 0) {
    doc += `## Classes

| Class | File | Documented | Complexity |
|-------|------|------------|------------|
${classes.map(({ block, file }) =>
  `| \`${block.name}\` | ${file.info.relativePath}:${block.startLine} | ${block.documentation ? '✅' : '❌'} | ${block.complexity || '-'} |`
).join('\n')}

`;

    for (const { block, file } of classes) {
      doc += generateBlockDoc(block, file.info.relativePath);
    }
  }

  if (interfaces.length > 0) {
    doc += `## Interfaces

| Interface | File | Documented |
|-----------|------|------------|
${interfaces.map(({ block, file }) =>
  `| \`${block.name}\` | ${file.info.relativePath}:${block.startLine} | ${block.documentation ? '✅' : '❌'} |`
).join('\n')}

`;
  }

  if (functions.length > 0) {
    doc += `## Functions

| Function | File | Parameters | Returns | Documented | Complexity |
|----------|------|------------|---------|------------|------------|
${functions.map(({ block, file }) =>
  `| \`${block.name}\` | ${file.info.relativePath}:${block.startLine} | ${block.parameters?.length || 0} | ${block.returnType || '-'} | ${block.documentation ? '✅' : '❌'} | ${block.complexity || '-'} |`
).join('\n')}

`;

    for (const { block, file } of functions) {
      doc += generateBlockDoc(block, file.info.relativePath);
    }
  }

  return doc;
}

function generateBlockDoc(block: CodeBlock, filePath: string): string {
  let doc = `### \`${block.name}\`

**File:** \`${filePath}:${block.startLine}\`
**Type:** ${block.type}
`;

  if (block.complexity) {
    doc += `**Complexity:** ${block.complexity} ${getComplexityIndicator(block.complexity)}\n`;
  }

  if (block.documentation) {
    doc += `\n${block.documentation}\n`;
  }

  if (block.parameters && block.parameters.length > 0) {
    doc += `
#### Parameters

| Name | Type | Optional | Default |
|------|------|----------|---------|
${block.parameters.map(p =>
  `| \`${p.name}\` | ${p.type || '-'} | ${p.optional ? 'Yes' : 'No'} | ${p.defaultValue || '-'} |`
).join('\n')}
`;
  }

  if (block.returnType) {
    doc += `\n#### Returns\n\n\`${block.returnType}\`\n`;
  }

  doc += '\n---\n\n';
  return doc;
}

function generateFileDoc(file: ParsedFile, includeSource: boolean): string {
  let doc = `# ${file.info.relativePath}

**Language:** ${file.info.language}
**Lines:** ${file.info.lines}
**Size:** ${formatBytes(file.info.size)}

`;

  if (file.imports.length > 0) {
    doc += `## Imports

${file.imports.map(i => `- \`${i.source}\`: ${i.items.join(', ')}`).join('\n')}

`;
  }

  if (file.exports.length > 0) {
    doc += `## Exports

${file.exports.map(e => `- \`${e.name}\` (${e.type})`).join('\n')}

`;
  }

  if (file.blocks.length > 0) {
    doc += `## Contents

`;

    for (const block of file.blocks) {
      doc += `### ${block.type}: \`${block.name}\`

**Lines:** ${block.startLine}-${block.endLine}
`;

      if (block.complexity) {
        doc += `**Complexity:** ${block.complexity} ${getComplexityIndicator(block.complexity)}\n`;
      }

      if (block.documentation) {
        doc += `\n> ${block.documentation.split('\n').join('\n> ')}\n`;
      } else {
        doc += `\n⚠️ *No documentation found*\n`;
      }

      if (block.parameters && block.parameters.length > 0) {
        doc += `\n**Parameters:**\n${block.parameters.map(p =>
          `- \`${p.name}\`${p.type ? `: ${p.type}` : ''}${p.optional ? ' (optional)' : ''}`
        ).join('\n')}\n`;
      }

      if (block.returnType) {
        doc += `\n**Returns:** \`${block.returnType}\`\n`;
      }

      if (includeSource) {
        doc += `\n<details>
<summary>Source Code</summary>

\`\`\`${file.info.language}
${block.content}
\`\`\`

</details>
`;
      }

      doc += '\n---\n\n';
    }
  }

  return doc;
}

function generateHealthReport(healthScore: HealthScore): string {
  return `# Codebase Health Report

> Auto-generated by DocuMate

## Overall Score: ${getHealthEmoji(healthScore.overall)} ${healthScore.overall}/100

${getHealthGrade(healthScore.overall)}

## Category Breakdown

| Category | Score | Status |
|----------|-------|--------|
| Documentation | ${healthScore.categories.documentation}/100 | ${getHealthEmoji(healthScore.categories.documentation)} |
| Complexity | ${healthScore.categories.complexity}/100 | ${getHealthEmoji(healthScore.categories.complexity)} |
| Structure | ${healthScore.categories.structure}/100 | ${getHealthEmoji(healthScore.categories.structure)} |
| Maintainability | ${healthScore.categories.maintainability}/100 | ${getHealthEmoji(healthScore.categories.maintainability)} |

## Issues (${healthScore.issues.length} total)

${healthScore.issues.length === 0 ? '✅ No issues found!' : ''}

${['error', 'warning', 'info'].map(severity => {
  const issues = healthScore.issues.filter(i => i.severity === severity);
  if (issues.length === 0) return '';

  return `### ${getSeverityEmoji(severity as any)} ${severity.charAt(0).toUpperCase() + severity.slice(1)}s (${issues.length})

${issues.map(issue =>
  `- **${issue.rule}**: ${issue.message}${issue.file ? `\n  - File: \`${issue.file}:${issue.line}\`` : ''}`
).join('\n')}
`;
}).filter(Boolean).join('\n')}

## Suggestions for Improvement

${healthScore.suggestions.length === 0 ? 'No suggestions - your code looks good!' :
  healthScore.suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

*Report generated on ${new Date().toISOString()}*
`;
}

function generateHTMLDocument(
  files: ParsedFile[],
  healthScore: HealthScore,
  projectName: string
): string {
  const totalFunctions = files.reduce((sum, f) =>
    sum + f.blocks.filter(b => b.type === 'function' || b.type === 'method').length, 0);
  const totalClasses = files.reduce((sum, f) =>
    sum + f.blocks.filter(b => b.type === 'class').length, 0);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${projectName} Documentation</title>
  <style>
    :root {
      --bg: #1a1a2e;
      --surface: #16213e;
      --primary: #0f3460;
      --accent: #e94560;
      --text: #eaeaea;
      --text-muted: #a0a0a0;
      --success: #4ade80;
      --warning: #fbbf24;
      --error: #f87171;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
    }
    .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
    header {
      background: linear-gradient(135deg, var(--primary), var(--surface));
      padding: 3rem 2rem;
      border-radius: 1rem;
      margin-bottom: 2rem;
    }
    h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
    .subtitle { color: var(--text-muted); font-size: 1.1rem; }
    .stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 1rem;
      margin: 2rem 0;
    }
    .stat-card {
      background: var(--surface);
      padding: 1.5rem;
      border-radius: 0.75rem;
      text-align: center;
      border: 1px solid rgba(255,255,255,0.1);
    }
    .stat-value { font-size: 2rem; font-weight: bold; color: var(--accent); }
    .stat-label { color: var(--text-muted); font-size: 0.9rem; }
    .health-score {
      background: var(--surface);
      padding: 2rem;
      border-radius: 1rem;
      margin: 2rem 0;
    }
    .score-circle {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      background: conic-gradient(var(--accent) ${healthScore.overall * 3.6}deg, var(--primary) 0deg);
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto 1rem;
    }
    .score-inner {
      width: 100px;
      height: 100px;
      border-radius: 50%;
      background: var(--surface);
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 1.5rem;
      font-weight: bold;
    }
    .categories { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-top: 1.5rem; }
    .category {
      text-align: center;
      padding: 1rem;
      background: var(--primary);
      border-radius: 0.5rem;
    }
    .category-score { font-size: 1.5rem; font-weight: bold; }
    .category-label { font-size: 0.8rem; color: var(--text-muted); }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid rgba(255,255,255,0.1);
    }
    th { background: var(--primary); font-weight: 600; }
    tr:hover { background: rgba(255,255,255,0.05); }
    code { background: var(--primary); padding: 0.2rem 0.4rem; border-radius: 0.25rem; font-size: 0.9rem; }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.5rem;
      border-radius: 0.25rem;
      font-size: 0.75rem;
      font-weight: 600;
    }
    .badge-success { background: var(--success); color: #000; }
    .badge-warning { background: var(--warning); color: #000; }
    .badge-error { background: var(--error); color: #000; }
    section { margin: 2rem 0; }
    h2 { margin-bottom: 1rem; color: var(--accent); }
    footer { text-align: center; padding: 2rem; color: var(--text-muted); }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${projectName}</h1>
      <p class="subtitle">Auto-generated documentation by DocuMate</p>
    </header>

    <div class="stats">
      <div class="stat-card">
        <div class="stat-value">${files.length}</div>
        <div class="stat-label">Files</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${files.reduce((sum, f) => sum + f.info.lines, 0).toLocaleString()}</div>
        <div class="stat-label">Lines of Code</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${totalFunctions}</div>
        <div class="stat-label">Functions</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${totalClasses}</div>
        <div class="stat-label">Classes</div>
      </div>
    </div>

    <section class="health-score">
      <h2>Health Score</h2>
      <div class="score-circle">
        <div class="score-inner">${healthScore.overall}</div>
      </div>
      <div class="categories">
        <div class="category">
          <div class="category-score">${healthScore.categories.documentation}</div>
          <div class="category-label">Documentation</div>
        </div>
        <div class="category">
          <div class="category-score">${healthScore.categories.complexity}</div>
          <div class="category-label">Complexity</div>
        </div>
        <div class="category">
          <div class="category-score">${healthScore.categories.structure}</div>
          <div class="category-label">Structure</div>
        </div>
        <div class="category">
          <div class="category-score">${healthScore.categories.maintainability}</div>
          <div class="category-label">Maintainability</div>
        </div>
      </div>
    </section>

    <section>
      <h2>Files</h2>
      <table>
        <thead>
          <tr>
            <th>File</th>
            <th>Language</th>
            <th>Lines</th>
            <th>Functions</th>
            <th>Classes</th>
          </tr>
        </thead>
        <tbody>
          ${files.map(f => `
          <tr>
            <td><code>${f.info.relativePath}</code></td>
            <td>${f.info.language}</td>
            <td>${f.info.lines}</td>
            <td>${f.blocks.filter(b => b.type === 'function' || b.type === 'method').length}</td>
            <td>${f.blocks.filter(b => b.type === 'class').length}</td>
          </tr>
          `).join('')}
        </tbody>
      </table>
    </section>

    ${healthScore.issues.length > 0 ? `
    <section>
      <h2>Issues</h2>
      <table>
        <thead>
          <tr>
            <th>Severity</th>
            <th>Rule</th>
            <th>Message</th>
            <th>Location</th>
          </tr>
        </thead>
        <tbody>
          ${healthScore.issues.slice(0, 20).map(issue => `
          <tr>
            <td><span class="badge badge-${issue.severity}">${issue.severity}</span></td>
            <td>${issue.rule}</td>
            <td>${issue.message}</td>
            <td>${issue.file ? `<code>${issue.file}:${issue.line}</code>` : '-'}</td>
          </tr>
          `).join('')}
        </tbody>
      </table>
    </section>
    ` : ''}

    <footer>
      <p>Generated by DocuMate on ${new Date().toISOString()}</p>
    </footer>
  </div>
</body>
</html>`;
}

function getHealthEmoji(score: number): string {
  if (score >= 80) return '🟢';
  if (score >= 60) return '🟡';
  if (score >= 40) return '🟠';
  return '🔴';
}

function getSeverityEmoji(severity: 'error' | 'warning' | 'info'): string {
  switch (severity) {
    case 'error': return '🔴';
    case 'warning': return '🟡';
    case 'info': return '🔵';
  }
}

function getComplexityIndicator(complexity: number): string {
  if (complexity <= 5) return '(low)';
  if (complexity <= 10) return '(moderate)';
  if (complexity <= 20) return '(high)';
  return '(very high ⚠️)';
}

function getHealthGrade(score: number): string {
  if (score >= 90) return '**Grade: A** - Excellent! Your codebase is well-maintained.';
  if (score >= 80) return '**Grade: B** - Good. Minor improvements recommended.';
  if (score >= 70) return '**Grade: C** - Fair. Several areas need attention.';
  if (score >= 60) return '**Grade: D** - Needs Work. Significant improvements needed.';
  return '**Grade: F** - Critical. Immediate attention required.';
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
